username = "Fit-Belt1935"
password = "Rishabh@12345"
client_id = "H2f8VSpd-8t5AoQSGZVVoA"
client_secret='c5PexU5V63uQYOGeMQWAz0pqG1FN0w'
user_agent="Reddit bot for bidding"
mongo_uri="mongodb+srv://root:root@cluster.if4vaf9.mongodb.net/?retryWrites=true&w=majority"
mongo_dbname="reddit"
mongo_comment_collection="comments"
mongo_post_collection="posts"
subreddit_name = "rktestingbtot"
